---
ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - COPYPASTE_JSCPD
  - MARKDOWN_MARKDOWNLINT
  - PYTHON_RUFF
  - REPOSITORY_GIT_DIFF
  - YAML_PRETTIER
  - YAML_YAMLLINT
  - YAML_V8R

VALIDATE_ALL_CODEBASE: true
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
FLAVOR_SUGGESTIONS: false
